from fastapi import FastAPI

app = FastAPI(
    title="{{PROJECT_NAME}}",
    description="Professional API generated by Archiforge",
    version="1.0.0"
)

@app.get("/")
async def root():
    return {"status": "Online", "framework": "FastAPI", "project": "{{PROJECT_NAME}}"}

@app.get("/health")
async def health_check():
    return {"status": "healthy"}