import React from 'react';

function App() {
  return (
    <div style={{ textAlign: 'center', marginTop: '50px', fontFamily: 'Arial' }}>
      <h1>🚀 Welcome to {{PROJECT_NAME}}</h1>
      <p>Generated by <strong>Archiforge</strong></p>
      <div className="card">
        <p>Edit <code>src/App.jsx</code> to start building your UI.</p>
      </div>
    </div>
  );
}

export default App;